<?php

namespace common\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use common\models\Post;

/**
 * PostSearch represents the model behind the search form of `common\models\Post`.
 */
class PostSearch extends Post
{
    /**
     * 给模型类添加属性
     * @return array
     */
    public function attributes()
    {
        return array_merge(parent::attributes(),['authorName']); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'status', 'create_time', 'update_time', 'author_id'], 'integer'],
            //给新添加的字段添加规则
            [['title', 'content', 'tags','authorName'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Post::find();
        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            //添加分页 排序等功能
            'pagination'=>['pageSize'=>3],
            'Sort'=>[
                'defaultOrder'=>[
                    'id'=>SORT_DESC
                ],
                //指定那些可以排序
                'attributes'=>['id','title']
            ]
        ]);
        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'post.id' => $this->id,
            'status' => $this->status,
            'create_time' => $this->create_time,
            'update_time' => $this->update_time,
            'author_id' => $this->author_id,
        ]);

        $query->andFilterWhere(['like', 'title', $this->title])
            ->andFilterWhere(['like', 'content', $this->content])
            ->andFilterWhere(['like', 'tags', $this->tags]);

       //  连接查询
        $query->join('INNER  JOIN', 'adminuser','adminuser.id = post.author_id');
        //var_dump($query);exit(0);
        //添加过滤的字段
        $query->andFilterWhere(['like','adminuser.username',$this->authorName]);
        // 排序
        $dataProvider->sort->attributes['authorName'] = [
            'asc'=>['adminuser.username'=>SORT_DESC],
            'desc'=>['adminuser.username'=>SORT_ASC],
        ];

        return $dataProvider;
    }
}
