<?php
/**
 * Created by PhpStorm.
 * User: ASUS
 * Date: 2017-03-21
 * Time: 18:29
 */

namespace frontend\component;
use yii\base\Widget;
use yii\helpers\Html;
class RecentCommentWeight extends Widget
{
    public $recentComments;

    public function init()
    {
        parent::init();
    }

    public function run()
    {
        $commentString='';

        foreach ($this->recentComments as $comment)
        {
            $commentString.='<div class="post">'.
                '<div class="title">'.
                '<p style="color:#777777;font-style:italic;">'.
                nl2br($comment->content).'</p>'.
                '<p class="text"> <span class="glyphicon glyphicon-user" aria-hidden="ture">
							</span> '.Html::encode($comment->user->username).'</p>'.

                '<p style="font-size:8pt;color:bule">
							《<a href="'.$comment->post->url.'">'.Html::encode($comment->post->title).'</a>》</p>'.
                '<hr></div></div>';
        }
        return  $commentString;
    }
}



//namespace frontend\component;
//
//use yii\base\Widget;
//
//class RecentCommentWeight extends Widget
//{
//    public $displaycomment = '';
//
//    public function init()
//    {
//        parent::init(); // TODO: Change the autogenerated stub
//    }
//
//    public function run()
//    {
//        /*foreach ($this->comment as $item) {
//            $displaycomment .= "<div class='post'>
//                    <p class='active'><span class='glyphicon glyphicon-user'></span>{$item->user->username}</p>
//                    <div>{$item->comment}</div>
//            </div>";
//        }
//        return $displaycomment;*/
//        $commentString='';
//
//        foreach ($this->recentComments as $comment)
//        {
//            $commentString.='<div class="post">'.
//                '<div class="title">'.
//                '<p style="color:#777777;font-style:italic;">'.
//                nl2br($comment->content).'</p>'.
//                '<p class="text"> <span class="glyphicon glyphicon-user" aria-hidden="ture">
//							</span> '.Html::encode($comment->user->username).'</p>'.
//
//                '<p style="font-size:8pt;color:bule">
//							《<a href="'.$comment->post->url.'">'.Html::encode($comment->post->title).'</a>》</p>'.
//                '<hr></div></div>';
//        }
//        return  $commentString;
//    }
//}