<?php
namespace frontend\component;
/**
 * Created by PhpStorm.
 * User: ASUS
 * Date: 2017-03-21
 * Time: 14:10
 */
class  TagsCloudWeight extends \yii\base\Widget
{
    public $tags;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 自定义样式 ，显示标签
     * @return string
     */
    public function run()
    {
        $tagString = '';
        $fontStyle = array(
            "6" => 'danger',
            "5" => 'info',
            "4" => 'warning',
            "3" => 'primary',
            "2" => 'success',
        );

        foreach ($this->tags as $tag => $weight) {
            $rand = rand(2, 6);
            /*$tagString .= '<a href="' . \Yii::$app->homeUrl . '?r=post/index&PostSearch[tags]' . $tag . '">
             <h' . $weight . ' style="display:inner-block;"><span class="label label-' . $fontStyle[$rand]  . '">'
                . $tag . '</span></h' . $weight . ' ></a>';*/


            /*  $tagString .= '<a href="' . \Yii::$app->homeUrl . '?r=post/index&PostSearch[tags]=' . $tag . '">
              <h' . $weight . ' style="display:inline-block;"><span class="label label-' . $fontStyle[$rand]  . '">'
                  . $tag . '</span></h' . $weight . ' ></a>';*/

            //美化路由
            $url = \Yii::$app->urlManager->createUrl(['post/index', 'PostSearch[tags]' => $tag]);

            $tagString .= '<a href="' . $url . '">
            <h' . $weight . ' style="display:inline-block;"><span class="label label-' . $fontStyle[$rand] . '">'
                . $tag . '</span></h' . $weight . ' ></a>';

            //echo $fontStyle[$weight].'<br>' ;;
        }
        // var_dump($tagString);exit();
        return $tagString;
    }
}